import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import ChatBot from "./ChatBot";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { SessionProvider } from "next-auth/react";
import SignIn from "./sign-in/page";
import SignUp from "./sign-up/page";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Milo - progressive overload app ",
  description: "Generated by Alec Squire",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* <SessionProvider session={session}>
          {!session ? <SignIn /> : <SignUp />} */}

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="flex flex-col justify-center items-center border-b">
            <div className="max-w-6xl w-full">
              <MainNav />
              <main className="flex flex-col items-center">
                <div className="max-w-6xl w-full">{children}</div>
              </main>
            </div>
          </nav>
          <ChatBot />
        </ThemeProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
