import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/Theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";

import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { SessionProvider } from "next-auth/react";
import Home from "./page";
// import { ContextProvider } from "@/context/ContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Milo - progressive overload app ",
  description: "Generated by Alec Squire",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* <ContextProvider> */}
          <nav className="flex flex-col justify-center items-center border-b">
            <div className="max-w-6xl w-full">
              <MainNav />
              <main className="flex flex-col items-center">
                <div className="max-w-6xl w-full">
                  {children}
                  <Toaster />
                </div>
              </main>
            </div>
          </nav>

          {/* </ContextProvider> */}
        </ThemeProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
